sudo: required
dist: trusty
language: cpp

env:
  global:
    - LANG="en_US.UTF-8"
    - COVERAGE=false

compiler:
  - gcc

# need gcc 4.9 and cmake
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      #- g++-4.9
      - cmake
      - lcov
  #sonarcloud
  sonarcloud:
    organization: "ark-game"
    token:
        secure: "a9ZtoUxCgJrSzfoIxaxpMtVszI26GrNIJSrLyEKnbq8JwwR2glv98C4bjjUx3tlAEHiB9H1meEoo6X4i2c+bJX4XapCenpGL4v0Lz0LtQ3nxbDIUy07hyqtrgGlS3f/Ywjx7ttOJU1RZevX9h5/uK8oO1zdz8i9p9zkXgp2UleM1TplQGdD736X80+MCivMdkE/J3TYseyYQ+a8JOEf5PrvIeDjrgAUM0tlm5nPfnCkFJ/R9FDrZBBprq61MKQDe1A1bIso4zFUcl8wPFG07hRauXLtl6MMSNsXVsYZ1BytOyBtnFiOMMMh9FGNTEHqW/tsABNLQOuPCQ1zv0gPz951ke7qrWOYB1amdvaJInDIO8qgsh5wT6NDyPktaIGTbGr/tlTUF7t+iKWxpkfqFCRsZcogfHSy0j0GoFr0xuMrNALS5d+yOOrVGbmilKUIXFszhqezsLRkcZtWgz4+2NPq39/ghZQr1xi7QBd+sDHfOJd34QExevHCthUfUdFuFHpfgewHnD1yXVMNnwmIEt7V6YgdAzsv9vSXlegKBt1ybWU3t78GWu4EHd+gHsT6Ki6kyJbqw89FE7DTOay2oEy6YA7q1vU3czC6DL8BIXlODMT+ccqSgA+cO4i/gNCHpY2DmjAdlDydAy+vrZrzfbjZSHArW3VFP5rEv74Bsfx4="
before_install:
  # run build_dep.sh
  - pwd
  - cd Dep
  - chmod -R 755 build_dep.sh
  - ./build_dep.sh
  - cd ..

install:
    #- sudo pip install --upgrade pip
    #- sudo pip install codecov
  
before_script:
  # cmake
  - if [-d "build" ]; then rm -rf build; fi
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_COVERAGE=ON ..

script:
  # make
  - build-wrapper-linux-x86-64 --out-dir bw-output make -j 4
  - cd $TRAVIS_BUILD_DIR/Frame
  #If you need debug log, plase add -X parameters
  - sonar-scanner
    
after_success:
  #- bash <(curl -s https://codecov.io/bash)
  
cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email:
    - nickyang1988@qq.com
    - 410274624@qq.com
