sudo: required
dist: trusty
language: cpp

env:
  global:
    - LANG="en_US.UTF-8"
    - COVERAGE=false

compiler:
  - gcc

# need gcc 4.9 and cmake
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      #- g++-4.9
      - cmake
      - lcov
  #sonarcloud
  sonarcloud:
    organization: "ark-game"
    token:
        secure: "mT56Sj2ebjbZ2uQOlNWM96WC+TG9RqZL5221oaMqagBDdcBTYwk0wdOgTl6CYukt7XYFyf1Okx96WF36hWiGJbLVDsrvB3hEgPwWMtEL1az66jNc/yWB1tCyMX+R+pJIQC7CK4MnKCoMAHaTdRBT8fCVxGaJtD6SdR1uI4VqREZO/FUq8Pa4qXwzY0XT64jGpe2gxKgRp4jAFGhTUngk3ePZ1NtGiTHpAscgNRJtn2pctJwxGQWGk3+z28XvZWlHvRAilkIfrHpfkiira6lo1Bx0cqlGo26d125xZ9otOgHA1OIcgLtaEpqRcrBGvK8BcJtm6p3ZCSH7BZGOzwnlzJJVzWIE8/8aDKe5eQGewNvGP7INWgu2YeF4okFR46L145Acz6m8UZ5zkaPrzQDyOpxge+Cq/XzatNQyyDHoBgrYJgBCM3COsVOngvamXAHi+v4U2TY7dpF8AwZCA1Sr1A85xDbZxxlw3/JPd9gbUO7dBXNrFuE/FOgNVkC/suEFvDHcJgbAgcVbQBMALqJT9YWXGE2JEL0nAAxMrbvfUs7B3RdRDhki3jodejIuNH/So1YgBJIZsa+V9Bv7XXUY8FMxKKCPiQb5+63fBkDpkk7my+VOABhfnMxSL/cg0k6HPmM28blYM8PsqwAUkrtTnyhchqVwjg2s1T5dO8v0URo="
before_install:
  # run build_dep.sh
  - pwd
  - cd Dep
  - chmod -R 755 build_dep.sh
  - ./build_dep.sh
  - cd ..

install:
    #- sudo pip install --upgrade pip
    #- sudo pip install codecov
  
before_script:
  # cmake
  - if [-d "build" ]; then rm -rf build; fi
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DENABLE_COVERAGE=ON ..

script:
  # make
  - build-wrapper-linux-x86-64 --out-dir bw-output
  - cd $TRAVIS_BUILD_DIR/Frame
  #If you need debug log, plase add -X parameters
  - sonar-scanner
    
after_success:
  #- bash <(curl -s https://codecov.io/bash)
  
cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email:
    - nickyang1988@qq.com
    - 410274624@qq.com
